_BASE_: "./Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN:
    - cabbage_train
  TEST:
    - cabbage_val
DATALOADER:
  NUM_WORKERS: 4
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  RPN:
    BATCH_SIZE_PER_IMAGE: 8
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.6
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 1
    BATCH_SIZE_PER_IMAGE: 8
SOLVER:
  STEPS: ()
  MAX_ITER: 1000
  BASE_LR: 0.00025
  IMS_PER_BATCH: 2
TEST:
  EVAL_PERIOD: 200
